// Developer Express Code Central Example:
// How to implement custom dropdown row editor for DXGrid
// 
// This example demonstrates how to edit grid row using the dropdown panel with
// editors generated automatically based on the underlying row data object. To see
// this approach in action, click the "Edit" hyperlink in the "#" grid column. To
// close dropdown panel click "Edit" again.
// This functionality is achieved by
// creating the attached behavior which generates the necessary DataRowTemplate for
// the grid row. The custom template can also be defined and assigned to the
// GridHelper.CustomTemplate property, so the custom template will be used instead
// the autogenerated template.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4798

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DXGrid.CustomDropdownRowEditor {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {
        public MainWindow() {
            InitializeComponent();
            this.dxGrid.ItemsSource = DataSample.GetData(1000);
        }

        private void Hyperlink_Click(object sender, RoutedEventArgs e)
        {
            var info = view.CalcHitInfo(e.OriginalSource as DependencyObject);
            dxGrid.SetMasterRowExpanded(info.RowHandle, !dxGrid.IsMasterRowExpanded(info.RowHandle));
        }
    }
}
