' Developer Express Code Central Example:
' How to implement custom dropdown row editor for DXGrid
' 
' This example demonstrates how to edit grid row using the dropdown panel with
' editors generated automatically based on the underlying row data object. To see
' this approach in action, click the "Edit" hyperlink in the "#" grid column. To
' close dropdown panel click "Edit" again.
' This functionality is achieved by
' creating the attached behavior which generates the necessary DataRowTemplate for
' the grid row. The custom template can also be defined and assigned to the
' GridHelper.CustomTemplate property, so the custom template will be used instead
' the autogenerated template.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4798
Imports System.Windows
Imports System.Windows.Controls

Namespace DXGrid.CustomDropdownRowEditor

    ''' <summary>
    ''' Interaction logic for MainWindow.xaml
    ''' </summary>
    Public Partial Class MainWindow
        Inherits Window

        Public Sub New()
            Me.InitializeComponent()
            Me.dxGrid.ItemsSource = DataSample.GetData(1000)
        End Sub

        Private Sub Hyperlink_Click(ByVal sender As Object, ByVal e As RoutedEventArgs)
            Dim info = Me.view.CalcHitInfo(TryCast(e.OriginalSource, DependencyObject))
            Me.dxGrid.SetMasterRowExpanded(info.RowHandle, Not Me.dxGrid.IsMasterRowExpanded(info.RowHandle))
        End Sub
    End Class
End Namespace
