' Developer Express Code Central Example:
' How to implement custom dropdown row editor for DXGrid
' 
' This example demonstrates how to edit grid row using the dropdown panel with
' editors generated automatically based on the underlying row data object. To see
' this approach in action, click the "Edit" hyperlink in the "#" grid column. To
' close dropdown panel click "Edit" again.
' This functionality is achieved by
' creating the attached behavior which generates the necessary DataRowTemplate for
' the grid row. The custom template can also be defined and assigned to the
' GridHelper.CustomTemplate property, so the custom template will be used instead
' the autogenerated template.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4798
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXGrid.CustomDropdownRowEditor.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DXGrid.CustomDropdownRowEditor.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DXGrid.CustomDropdownRowEditor.Properties.Settings())), DXGrid.CustomDropdownRowEditor.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DXGrid.CustomDropdownRowEditor.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
